# Usar una imagen base oficial de Node.js
FROM node:22-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar solo el package.json y package-lock.json para optimizar la caché de Docker
COPY package*.json ./

# Instalar dependencias solo de producción (sin dependencias de desarrollo)
RUN npm install --production

# Copiar el resto de los archivos de la aplicación
COPY . .

# Establecer las variables de entorno
ENV NODE_ENV=production

# Exponer el puerto 3000 (ajusta esto a tu aplicación)
EXPOSE 3000

# Comando para ejecutar la aplicación en producción
CMD ["node", "index.js"]