GET http://localhost:3000/ HTTP/1.1

### 
POST http://localhost:3000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "mikeJoya@ejemplo.com",
    "password": "123"
}
### 
POST http://localhost:3000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "mikeJoya@ejemplo.com",
    "password": "123dqwdqwd"
}

### 
POST http://localhost:3000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "1234@ejemplo.com",
    "password": "$2a$10$UgbmiGD6tI3CmOy5hgmLfujBJGJge55uuapvTaotJ/2JXMvKXUFHG"
}


###
GET http://localhost:3000/api/v1/user HTTP/1.1
Content-Type: application/json


###
POST http://localhost:3000/api/v1/user HTTP/1.1
Content-Type: application/json

{
    "email": "yisusGG@ejemplo.com",
    "password": "123456"
}


###
GET http://localhost:3000/api/v1/rawMaterials HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/v1/supplier HTTP/1.1
Content-Type: application/json

### 
GET http://localhost:3000/api/v1/categories/raw HTTP/1.1
Content-Type: application/json

###
PATCH  http://localhost:3000/api/v1/rawMaterials/3 HTTP/1.1
Content-Type: application/json

{
    "nombre_insumo": "Tela de Algodoncho",
    "color_insumo": "rosado"
}

###
DELETE  http://localhost:3000/api/v1/rawMaterials/3 HTTP/1.1
Content-Type: application/json