import { z } from "zod";

export const formRegisterSchema = z.object({
  handleSubmit: z.function().args(z.any()).returns(z.any()),
  products: z.array(z.any()),
  setProducts: z.function(),
  name: z.string(),
  price: z.union([z.string(), z.number()]),
  editIndex: z.number().nullable(),
  search: z.string(),
  filteredProducts: z.array(z.any()).optional(),
  setName: z.function(),
  setPrice: z.function(),
  setEditIndex: z.function(),
  setSearch: z.function(),
  code: z.string(),
  setCode: z.function(),
  stock: z.union([z.string(), z.number()]),
  setStock: z.function(),
  category: z.string(),
  setCategory: z.function(),
  weight: z.union([z.string(), z.number()]),
  setWeight: z.function(),
  textButton: z.string(),
  isListClient: z.boolean(),
  setIsListClient: z.function(),
  address: z.string(),
  setAddress: z.function(),
  numberPhone: z.string(),
  setNumberPhone: z.function(),
  co: z.string(),
  setCo: z.function(),
  user: z.any(),
  setUser: z.function(),
  clients: z.array(z.any()),
  setClients: z.function(),
  filteredClients: z.array(z.any()),
  isListMaterials: z.boolean(),
  typeMaterial: z.string(),
  setTypeMaterial: z.function(),
  color: z.string(),
  setColor: z.function(),
  filteredMaterials: z.array(z.any()),
  materials: z.array(z.any()),
  setMaterials: z.function(),
  setIdSupplier: z.function(),
});
