# Etapa 1: build de la app
FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build  # Esto generará la carpeta 'dist'

# Verifica que la carpeta 'dist' esté presente después del build
RUN ls -l /app/dist  # Verifica que la carpeta 'dist' esté presente

# Etapa 2: servir con nginx
FROM nginx:alpine

# Crear el directorio en caso de que no exista
RUN mkdir -p /usr/share/nginx/html

# Copiar los archivos generados por Vite a nginx
COPY --from=build /app/dist /usr/share/nginx/html
# Configuracion que necesita ngixn para las rutas
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]